### ISSUE TITLE
ignore .swp file

### ISSUE THREAD

**Issue by liyingjun** [kata-containers/agent#118]
.swp file which generated by editor should be ignored

**Comment by gnawux** [comment]
I think you may configure a global git ignore configuration in your local host for the IDE/editor related files.

**Comment by liyingjun** [comment]
@gnawux thanks for suggestion, it was suggested by jodh-intel from https://github.com/kata-containers/proxy/pull/42

**Comment by gnawux** [comment]
@liyingjun thanks, I will suggest the same in that PR

**Comment by caoruidong** [comment]
So we can close it now
