### ISSUE TITLE
Document all protocol elements

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/agent#150]
We should document *all* Messages and all message members for the `*.proto` files in:

- https://github.com/kata-containers/agent/tree/master/protocols/grpc

This will:

- improve comprehension, thus making it easier to understand and review the protocol
  (which might indirectly help ensure the protocol is as safe as possible).
- help avoid issues like #147.

Additional to the description, we should pay particular attention to `string` fields due to their increased flexibility (and thus increased ability to confuse):

- What is the format of each string member?
- Can the value be `""`? If so, what does it mean?
- Are there any other "special" values (like the terrible golang `net.IP` `"<nil>"` value)?

Example where we have ambiguity:

```
message StringUser {
	string uid = 1;
	string gid = 2;
	repeated string additionalGids = 3;
}
```

Are those member values numbers encoded as strings (`"3"`, `"1000"`, `"0"`)? Or can they also (?) be specified as symbolics (`"adm"`, `"james"`, `"root"`)?

**Comment by egernst** [comment]
@jodh-intel - PTAL and update issue w/ current relevance.  AFAIU we have protocol documented now, but perhaps not at the detail you are hoping for.  Please clarify.

/cc @amshinde

**Comment by jodh-intel** [comment]
Most grpc `message` fields are now documented - we seem to have got into the groove of explaining all new types. Some of the older `message` types are still undocumented at the field level but are generally obvious. If there is confusion for these older ones, let's updated as that arises.

Closing.
