### ISSUE TITLE
Skip more tests when running as non-root user

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/agent#177]
Some of the tests are failing under Travis as they are running as a non-root user, but the tests require `root` privileges.

**Comment by grahamwhaley** [comment]
Just a note for anybody looking to fix these - ideally we'd fix by using `sudo`, and not running them as the root user - try to elevate priv to root for the shortest duration necessary.

**Comment by jodh-intel** [comment]
We actually already do that. See the full description on #178.
