### ISSUE TITLE
Change route gRPC API from imperative to declarative

### ISSUE THREAD

**Issue by mcastelino** [kata-containers/agent#19]
Today we add/delete routes. However this will not work for plugins such as PTP which manipulate routes in non standard manner. So routes API should be performed one shot using update/set Routes.

For more details

https://github.com/containers/virtcontainers/issues/500

**Comment by egernst** [comment]
Initial implementation works on a route at a time.  Will address this next by updating routes in a single shot.  To avoid conflict, the first step of this update will be to clear out all pre-existing routes.  It is assumed that this UpdateRoutes call will be made after the interfaces (and their addresses) are setup.

**Comment by egernst** [comment]
Closed by https://github.com/kata-containers/agent/pull/148
