### ISSUE TITLE
Implement sandbox shared PID namespace support

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/agent#20]
We need a way to launch all containers in the same PID namespace in case we get the flag `SandboxPidns` when `CreateSandbox()` is called.

**Comment by sboeuf** [comment]
This is going to be supported by starting a `pause` binary from the call to `CreateSandbox()`. This binary will be `ForkExec()` into a specific PID namespace we will choose the name of. This process will become the init(PID1) of this namespace. This way, we can start a bunch of containers into the same PID namespace without having this namespace being destroyed when some container processes terminate.

**Comment by laijs** [comment]
net/ipc/pid/uts are all suggested to be created for the sandbox init process.
And let the containers join in when requested. (net and uts ns are mandatory to join)

**Comment by laijs** [comment]
see #54

**Comment by sboeuf** [comment]
net namespace is a pretty complicated case...
