### ISSUE TITLE
Long delay between first stdio

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/agent#215]
When creating new container, there is a long delay between the first `ReadStdout` and the first `WriteStdin` requests. E.g., `2018-04-11T08:14:00.656058047Z` vs. `2018-04-11T08:15:15.088203739Z`

> Apr 11 16:14:01 macbeth kata-proxy[92953]: time="2018-04-11T16:14:01.273133901+08:00" level=info msg="time=\"2018-04-11T08:14:00.656058047Z\" level=debug msg=\"new request\" name=kata-agent pid=1 req=\"container_id:\\\"f03b948dacb9652bc22ffe1f18abf2e9f558bdce0474156394c6bfe75c2f0050\\\" exec_id:\\\"f03b948dacb9652bc22ffe1f18abf2e9f558bdce0474156394c6bfe75c2f0050\\\" len:32768 \" request=/grpc.AgentService/ReadStdout source=agent\n" name=kata-proxy pid=92953 source=agent
Apr 11 16:15:15 macbeth kata-proxy[92953]: time="2018-04-11T16:15:15.704613909+08:00" level=info msg="time=\"2018-04-11T08:15:15.088203739Z\" level=debug msg=\"new request\" name=kata-agent pid=1 req=\"container_id:\\\"f03b948dacb9652bc22ffe1f18abf2e9f558bdce0474156394c6bfe75c2f0050\\\" exec_id:\\\"f03b948dacb9652bc22ffe1f18abf2e9f558bdce0474156394c6bfe75c2f0050\\\" data:\\\"\\\\r\\\" \" request=/grpc.AgentService/WriteStdin source=agent\n" name=kata-proxy pid=92953 source=agent

**Comment by amshinde** [comment]
@bergwolf Is this still relevant?
