### ISSUE TITLE
Make sure that it is possible to open two netlink sockets to listen to udev events.

### ISSUE THREAD

**Issue by amshinde** [kata-containers/agent#216]
With our current implementation of uevent package, if two netlink sockets are opened at the same time for listening to uevents, we get a netlink error that the address is in use. This is because we use the Pid of the process in assigning the socket address, which results in conflicts.
https://github.com/kata-containers/agent/blob/06ce85905e514591dc9036ae1b7e32acd2f48022/pkg/uevent/uevent.go

 Instead allow kernel to choose socket address.

**Comment by sboeuf** [comment]
Oh, so you're gonna provide `PID = 0` ?
