### ISSUE TITLE
Agent can't mount net_cls,net_prio

### ISSUE THREAD

**Issue by keloyang** [kata-containers/agent#250]
# Description of problem
I want to use agent as init, but I find it  can't mount net_cls,net_prio with https://github.com/kata-containers/linux.git. If I change the kernel to redhat-3.10 kernel, it works.

# How to reproduce
## build initrd.img
```
cp kata-agent init
echo init | cpio -H newc -o | gzip -9  > initrd.img
```
## run the qemu with kata-containers/linux-kernel
```
qemu-system-x86_64 -kernel kata-containers-kernel -initrd initrd.img --append console=ttyS0  -nographic
```
we will see the following err,
```
ERRO[0000] fatal error                                   name=kata-agent panic="initAgentAsInit() error: rpc error: code = Internal desc = Could not mount cgroup to /sys/fs/cgroup/net_cls,net_prio: no such file or directory" pid=1 source=agent
ERRO[0000] --- contention:                               name=kata-agent pid=1 source=agent
ERRO[0000] cycles/second=1995363498                      name=kata-agent pid=1 source=agent
ERRO[0000] goroutine 1 [running]:                        name=kata-agent pid=1 source=agent
ERRO[0000] runtime/pprof.writeGoroutineStacks(0x11907c0, 0xc4201596c0, 0x0, 0x0)  name=kata-agent pid=1 source=agent
ERRO[0000]      /usr/local/go/src/runtime/pprof/pprof.go:603 +0x79  name=kata-agent pid=1 source=agent
ERRO[0000] runtime/pprof.writeGoroutine(0x11907c0, 0xc4201596c0, 0x2, 0x0, 0x0)  name=kata-agent pid=1 source=agent
ERRO[0000]      /usr/local/go/src/runtime/pprof/pprof.go:592 +0x44  name=kata-agent pid=1 source=agent
ERRO[0000] runtime/pprof.(*Profile).WriteTo(0x117ec80, 0x11907c0, 0xc4201596c0, 0x2, 0x0, 0x0)  name=kata-agent pid=1 source=agent
```

on the other hand ,if I change to the redhat kernel, the problem will be eliminated.
```
qemu-system-x86_64 -kernel /boot/vmlinuz-3.10.0-514.35.4.7.x86_64  -initrd initrd.img --append console=ttyS0  -nographic
```

**Comment by bergwolf** [comment]
@keloyang then I'd say it's your kernel config issue. You need to at least enable proper cgroup and namespace support to allow kata agent to work.

If you seek to minimize baImage size, I agree that some of the kata kernel configs are must, but the cgroup and namespace ones are essential.

**Comment by keloyang** [comment]
@bergwolf I don't cut cgroup and namespace, these are essential for container. with the cutdown kernel，the kata container work.

It doesn't seem very good to use hard code, and sometimes it  maybe not work, and I think it's better to read cgroup subsystem info from /proc/cgroups， WDYT ?

**Comment by bergwolf** [comment]
@keloyang The error message `Could not mount cgroup to /sys/fs/cgroup/net_cls,net_prio: no such file or directory` indicated that your kernel does not have net cls and net prio cgroup support. So you did cut down cgroup support, to be specific `CONFIG_CGROUP_NET_PRIO` and `CONFIG_CGROUP_NET_CLASSID`.

If you get a container spec that sets them, the kata agent will fail to create the container. I'm sorry that we don't just want to boot kata agent on any kernel. There are minimal kernel feature requirements that are essential for kata agent to work properly.

**Comment by keloyang** [comment]
@bergwolf  CONFIG_CGROUP_NET_PRIO is root cause which lead to mount net_cls,net_prio failed.  thank you.

but I think the key issue is how to mount cgroup , not kernel cut down.
Is it better to mount cgroup with hard code, or read cgroup info from /proc/cgroups and then do mount?

**Comment by bergwolf** [comment]
@keloyang These cgroups are necessary for proper OCI container spec support. If we just mount whatever is there in `/proc/cgroups`, the instance may loses cgroups relevant OCI compatibilities.

That said, do you have a use case for kata containers that requires **no** cgroups support? If you do, we may consider loosen the restriction and allow kata agent to start without cgroups support. Of course the users would then need to be prepared for failures if they create containers with cgroups limits in the spec, or we add a kata cli config option to remove all cgroups limits from container spec when calling kata agent to create new containers.

**Comment by keloyang** [comment]
@bergwolf  I think cgroup is 
cut down the kernel config is my use case, e.g.

**Comment by keloyang** [comment]
@bergwolf  I think cgroup is  necessary for OCI , but not every cgroup subsystem. refer to https://github.com/opencontainers/runtime-spec/blob/master/schema/config-linux.json#L187

cut down the kernel config is my use case, e.g.  remove CONFIG_CGROUP_NET_PRIO from kernel config, using the origin hard code, qemu can't start kata-container because of agent'failing, but if agent get cgoup info from /proc/cgroups and then mount, qemu can start kata-container successfully.

on the other hand, It's not a good experience that give the hard code as a hard limit to let user use all cgroup subsystems. maybe it better to give the choice to the user.

**Comment by bergwolf** [comment]
@keloyang These cgroups are **REQUIRED** to properly support the future container creation with cgroups limits. If you remove `CONFIG_CGOUP_NET_PRIO` from guest kernel, kata agent will fail to create a container that specifies it. See https://github.com/opencontainers/runc/blob/master/libcontainer/configs/cgroup_linux.go#L118

And why do you remove `CONFIG_CGROUP_NET_PRIO` specifically but keep all the other cgroups configs in your kernel? Sorry I don't think we want to support removing random essential kernel configs.

> on the other hand, It's not a good experience that give the hard code as a hard limit to let user use all cgroup subsystems. maybe it better to give the choice to the user.

I agree that we can leave the choice to the user. That's what I meant in the earlier comment by adding a new kata cli config. But the switch is whether to have no cgroups support at all, instead of removing a single random control group while supporting others. Both kata runtime and kata agent needs updates to support such a use case. If you seek smaller kernel binary no matter what, it serves the same purpose by removing all cgroups support within the guest.

**Comment by keloyang** [comment]
@bergwolf  runc is just a oci-runtime implement, but kata-container use runc' libcontainer, so we still can take libcontainer's code for example.
 Is CONFIG_CGOUP_NET_PRIO  necessary for kata-container to start?
reffer to https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/fs/apply_raw.go#L132
```
132    for _, sys := range subsystems { 
133 		// TODO: Apply should, ideally, be reentrant or be broken up into a separate 
134 		// create and join phase so that the cgroup hierarchy for a container can be 
135 		// created then join consists of writing the process pids to cgroup.procs 
136 		p, err := d.path(sys.Name()) 
137 		if err != nil { 
138 			// The non-presence of the devices subsystem is 
139 			// considered fatal for security reasons. 
140 			if cgroups.IsNotFound(err) && sys.Name() != "devices" { 
141 				continue 
142 			} 
143 			return err 
144 		} 
```
 if CGOUP_NET_PRIO  is not exist , libcontainer will skip, but if devices cgroup subsystem is not exist, libcontainer will return err. So CONFIG_CGOUP_NET_PRIO is not  necessary for kata-container to start in theory, and actually I have a try, without CGOUP_NET_PRIO , kata-container still work.

thank for your agreement that we can leave the choice to user, I don't understand  adding a new kata cli config, but we can't  have no cgroups support, the code above show that devices subsystem is necessary . 

So I think read cgroup info from /proc/cgroups is a better way, thanks .

**Comment by bergwolf** [comment]
@keloyang Thanks for the pointer. Good to know that libcontainer only requires devices cgroups and all other control groups are optional. Now I agree with you that we should read from `/proc/cgroups` and please still make sure that agent init fails when devices cgroup is not supported.

**Comment by bergwolf** [comment]
This is a bit too libcontainer internal dependent but we are always tied to one specific libcontainer version so I can live with it. Please add a few comments on why we fail on devices cgroup absence, with a pointer to the libcontainer code in case we ever need to revisit it later.

**Comment by bergwolf** [comment]
@keloyang 
> actually I have a try, without CGOUP_NET_PRIO , kata-container still work.

Did you try to create a container with net priority cgroup resource limit on such a kernel w/o CGOUP_NET_PRIO?

**Comment by keloyang** [comment]
![default](https://user-images.githubusercontent.com/11223367/40405422-18416a84-5e4c-11e8-9636-a892b4d81029.JPG)

**Comment by keloyang** [comment]
@bergwolf test kata-container start w/o devices
in agent , skip the mount of /sys/fs/cgroup/devices
```
root@ubuntu:~/workspace/go/src/github.com/kata-containers/agent# git diff
diff --git a/agent.go b/agent.go
index 09105ea..e043bfe 100644
--- a/agent.go
+++ b/agent.go
@@ -651,6 +651,9 @@ var initRootfsMounts = []initMount{
 // when this agent has been run as the init process.
 func initAgentAsInit() error {
        for _, m := range initRootfsMounts {
+               if m.dest == "/sys/fs/cgroup/devices" {
+                       continue
+               }
                if err := os.MkdirAll(m.dest, os.FileMode(0755)); err != nil {
                        return err
                }
```
and then ,run kata-container will fail,
```
[root@localhost linux]# docker run --rm -it --runtime kata-runtime busybox sh
docker: Error response from daemon: oci runtime error: rpc error: code = Internal desc = Could not run process: container_linux.go:348: starting container process caused "process_linux.go:279: applying cgroup configuration for process caused \"mountpoint for devices not found\"".
```

**Comment by bergwolf** [comment]
@keloyang cool. Thanks for double checking!

**Comment by keloyang** [comment]
@bergwolf PTAL https://github.com/kata-containers/agent/pull/244
thanks.
