### ISSUE TITLE
yamux: keepalive failed: i/o deadline reached for proxybuiltin

### ISSUE THREAD

**Issue by lifupan** [kata-containers/agent#294]
# Description of problem

When kata is integrated into hyper, which uses the proxybuiltin mode. 
Once do  hyperctl pause <pod id>, which will pause the sandbox. 
After pause about 30s, builtin proxy will complain of "yamux: keepalive failed: i/o deadline reached"

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

---

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by gnawux** [comment]
@grahamwhaley Actually this PR is solving a different issue other than #263. Fupan is come from hyper.sh team and #263 is applied when we did the test, which is help but could not solve the issue.

**Comment by grahamwhaley** [comment]
Ah, I see - thx. We have just too many yamux's in flight - see: https://github.com/kata-containers/proxy/pull/71/files which is also related then.
Is this another yamux we should try to hook the logger for then similar to https://github.com/kata-containers/proxy/pull/89 etc.

**Comment by gnawux** [comment]
@grahamwhaley yep
