### ISSUE TITLE
Missing APIs

### ISSUE THREAD

**Issue by laijs** [kata-containers/agent#3]
hyperd depends on such hyperstart APIs:

- portmapping
  - Configured in CreateSandbox to setup portmapping
- ReadFile/WriteFiles
     Read/Write from a container, it is unused now.
   - ~update /etc/hosts~
- hyperstart-exec
    execute a process in the vm rather than in container. currently used for:
  - update portmapping
  - ipvs operations
  - `hyperctl exec --vm` peek/do something inside the vm. debug only.

In one words, more network APIs needs to be added and cover the above requirements.
(except the case for `hyperctl exec --vm`, but do we need to add some debug facilities for debug?)

**Comment by gnawux** [comment]
I am thinking about an API or a pair of APIs for socket passing, i.e. implement mapping a unix socket to guest, such as docker.sock . Could this be done with ReadFile/WriteFile?

**Comment by laijs** [comment]
I don't think ReadFile/WriteFile still needed. It is only used for updating /etc/hosts.
In docker case, /etc/hosts is always keeping updated via 9pfs+bindmount.
In other cases, we should introduce proper API for it.

**Comment by laijs** [comment]
I'm sorry, /etc/hosts was also switched to 9pfs+bindmount in hyperd/hyper.sh.

9pfs-less feature is also in demand. We should provide some APIs to enable updating /etc/hosts, /etc/resolv.conf in such cases.

**Comment by egernst** [comment]
Are these addressed with https://github.com/kata-containers/documentation/blob/master/design/kata-api-design.md?

If you agree, let's close this.

**Comment by jodh-intel** [comment]
Re-ping.
