### ISSUE TITLE
client: speed up agent dialer

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/agent#320]
The grpc dialer has a default 1 second backoff on the first connection failure. And it kills kata containers creation speed because we try to connect before knowing for certain that the agent is up and serving.

**Comment by grahamwhaley** [comment]
Ooh, nice find. Be great to see how that changes our timings :-)

**Comment by bergwolf** [comment]
@grahamwhaley As mentioned in #321, it speeds up kata container creation by around 0.5 second (w/o vm templating) or 1 second (w/ vm templating).

**Comment by jon** [comment]
IIUC the agent listens for an incoming vsock connection and the runtime connects, retrying until the agent is actually booted and listening.

I may have misunderstood the code, but to me, this feels backwards. The runtime could be "always listening" and inject (via kernel command line) an address for the agent to connect to. This would allow the agent to connect at the first possible moment to an already-listening endpoint. That would seem to minimize the time to connect while also avoiding retries. If a connection in the other direction is desired, the agent could make a single RPC over this channel "Connect to me on <address>" at which point the runtime could make a connection that it expected to succeed on the first try.

Alternatively, override the Dialer on both sides: have the runtime "Dial" by listening, and have the Agent "Listen" by dialing. It would be a strange abuse of Go's Dialer/Listener semantics, but it might accomplish the above with a minimum need for retries and trying to race to speed up connection initiation.

**Comment by sboeuf** [comment]
@jon 
>The runtime could be "always listening" and inject (via kernel command line) an address for the agent to connect to. This would allow the agent to connect at the first possible moment to an already-listening endpoint.

We're gonna move soon to the hotplug of the serial/vsock communication channel into the VM, after this one got started, meaning we have no way to tell the agent when this is going to be ready. And at the time the kernel parameter is passed, the socket might not have been hotplugged yet.
