### ISSUE TITLE
wait a bit in RemoveContainer

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/agent#333]
@lifupan hit an issue that if RemoveContainer is called right after SignalProcess(SIGKILL), the container process might be still running and container `Destroy()` will fail.

**Comment by sboeuf** [comment]
@bergwolf that's what the shim is here for. You should wait for the shim to return the exit code before you try to remove the container.

**Comment by bergwolf** [comment]
@sboeuf This is for containerd shimv2. It uses buildin proxy and shim so there is no standalone shim process to wait on.

**Comment by sboeuf** [comment]
@bergwolf sure I understand that, but there is a go routine waiting for this, right ?

**Comment by bergwolf** [comment]
@sboeuf The problem is kata runtime `container.stop()`. It kills the container process and then removes the container w/o waiting. OTOH, we cannot wait there either because otherwise if there is another waiter, it cannot get the container exit status.

@lifupan I agree that we should move container cleanup codes to `container.delete()` but it won't help solving this issue, unless you require `container.wait()` being always called before `container.delete()` in which case `container.stop()` become meaningless since it does the same thing as `container.kill()`. And container state machine becomes complicated because `wait()` is required to get a container to transit to STOPPED state.

**Comment by lifupan** [comment]
@bergwolf  Yes,  previously I thought we can require the container.wait() being always called before container.delete(). If you guys think this will complicated the state machine, I agree with you on the  approach to make WaitProcess reentrant you mentioned in https://github.com/kata-containers/agent/pull/334.
