### ISSUE TITLE
Add "make proto" to CI build

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/agent#340]
We should have a CI test to ensure it is always possible to regenerate `protocols/grpc/agent.proto` from `protocols/grpc/agent.pb.go` (and the same for the other `*.proto` files).

This should be as simple as adding `make proto` to `.ci/run.sh`.

/cc @WeiZhang555.

**Comment by WeiZhang555** [comment]
I like this idea, thanks Jame for raising this! @jodh-intel
