### ISSUE TITLE
Write OCI spec to a file within the guest

### ISSUE THREAD

**Issue by eguzman3** [kata-containers/agent#349]
In order to comply with the OCI specification, the agent should write the OCI specification to a 'config.json' file within the guest container's bundle path.

This issue was discovered when trying to use an existing OCI hook within the guest. This hook reads the bundle path from the `HookState` passed over stdin, then attempts to open `/path/to/bundle/config.json` which doesn't exist because the bundle path is wrong and because `config.json` is never written. The reason the cwd needs to be changed is that `CreateLibcontainerConfig` sets the bundle path to cwd:
https://github.com/kata-containers/agent/blob/5765593309eab087598c093ff226500af158df9c/vendor/github.com/opencontainers/runc/libcontainer/specconv/spec_linux.go#L157 
which in this case is `/` so this is what the OCI hooks end up getting instead of `/run/kata-containers/shared/containers/<hash>/`

**Comment by sboeuf** [comment]
Why do you want the agent to do such a thing? The agent is running inside the guest OS, and there is no reason to do what you're suggesting.
I can see that you mentioned about the OCI hooks, but it makes no sense to run them inside the guest OS anyway since they are expected to run in the host.

**Comment by jodh-intel** [comment]
Yes, picking over https://github.com/opencontainers/runtime-spec/blob/master/config.md, the crucial part is:

> Hooks MUST be executed in the runtime namespace.

**Comment by eguzman3** [comment]
@sboeuf @jodh-intel These hooks are intended to be executed on the guest and are separate from those executed on the host. I am assuming the hooks will be added to that directory at the time of rootfs image creation. The use case for this is trying to leverage this existing OCI hook: https://github.com/NVIDIA/nvidia-container-runtime
