### ISSUE TITLE
Shall we separate onlineCPUMem to onlineCPU and onlineMem

### ISSUE THREAD

**Issue by linzichang** [kata-containers/agent#357]
@sboeuf @jodh-intel @bergwolf @clarecch 
About the question mentioned in #331 , we can talk and get a decision here.

**Comment by jodh-intel** [comment]
This discussion seems to hinge on whichever of the following is most important:

- *clarity / discreteness:*

  Have separate gRPC calls for each operation:
  - `OnlineCPU()`.
  - `OnlineMem()`.

   Disadvantages:
   - 1 rpc call / resource. That might be a problem if we end up having to support a lot of different resources, all with their own gRPC call.

- *efficiency:*

  - `OnlineCPUMem()`.

    Bundle functionality together to minimise gRPC calls.

  Disadvantages:

   - current name precludes supporting additional resources in the future.
   - current design is arguably a little confusing in the way it determines which resources need onlining.

# Compromise solution?

What about the following:

```
message OnlineResourcesRequest {

    // Define resources as bit values
    enum Resources {
        OnlineNothing = 0x00; // required by proto3
        OnlineCPU = 0x01;
        OnlineMem = 0x02;
        OnlineFoo = 0x04;
                :
    }

    // Used to determine which Resources need to be onlined.
    //
    // For example, the value 0x05 would be equivalent to (OnlineCPU + OnlineFoo).
    fixed64 ResourceBitfield = 1;

    bool wait = 2;
    uint32 nb_cpus = 3;
    bool cpu_only = 4;
   
    // Future:
    ${type} ${resource} = 5;
        :
}

rpc OnlineResources(OnlineResourcesRequest) returns (google.protobuf.Empty);
```

Advantages:

- Still only requires a single call.
- Simple to understand (once you comprehend `ResourceBitfield`).
- Extensible if we need to online other resources in the future.

Disadvantages:

- Uses enums which can apparently be problematic.

Whatever we decide, I think we should prefer to focus on clarity unless the alternative is (provably) compelling.

# Thoughts

How about  we formally review the `*.proto` files? That would allows use to:

- Satisfy ourselves that we're adhering to best practise.
- Ensure we're in good shape should future changes be necessary.
- Document the protocols more fully as we go (https://github.com/kata-containers/agent/issues/150).

It would be great to get input from some gRPC experts here. This would be a good conversation to have at an Architecture Committee meeting I think.

/cc @jon

Related: https://github.com/kata-containers/documentation/pull/196

**Comment by linzichang** [comment]
I also think about "single call" solution. Just a little problem(probably), different resource may need different request and response. This will make struct of `OnlineResourcesRequest` and `OnlineResourcesResponse` bigger. But maybe just a concern since only CPU and memory need to be online in a long time.

**Comment by jodh-intel** [comment]
@linzichang - that is a good point! I wonder if we should create an explicit `OnlineResourcesResponse` message that returns an empty message initially? I don't know if that would make gRPC protocol compatibility simpler if we ever needed to return values [*] for a particular resource?

---
[*] - at which point we could add some fields to the empty `OnlineResourcesResponse` message.

**Comment by linzichang** [comment]
@jodh-intel Yes, I agree to create an explicit `OnlineResourcesResponse`.

**Comment by bergwolf** [comment]
What about automatic online with uevents? I tested some change and it works perfectly for me. We are not waiting for online command in kata-runtime anyway. See https://github.com/bergwolf/kata-agent/commit/d7b5a17d939c6d574407f539379afb0ecef6ac73

**Comment by bergwolf** [comment]
Then we can deprecate the onlinecpumem RPC and eventually remove it after a few releases.

**Comment by linzichang** [comment]
I think about udev too. It's very smooth, but we don't know whether online is successful or not. Need to find the result from the log in another time. I wonder if this is acceptable?

**Comment by clarecch** [comment]
Now we have both udev and onlinecpumem RPC working. 
In case we hotplug some cpu and memory to guest, in fact some of them will be online by udev and the others online by onlinecpumem RPC. It seems to be no problem on the surface, but in fact there are some conflicts between udev and onlinecpumem RPC.
```
func onlineCPUResources(nbCpus uint32) error {
	resource := onlineResource{
		sysfsOnlinePath: sysfsCPUOnlinePath,
		regexpPattern:   cpuRegexpPattern,
	}

	var count uint32
	for i := uint32(0); i < onlineCPUMaxTries; i++ {
		r, err := onlineResources(resource, int32(nbCpus-count))
		if err != nil {
			return err
		}
		count += r
		if count == nbCpus {
			return nil
		}
		time.Sleep(onlineCPUMemWaitTime)
	}

	return fmt.Errorf("only %d of %d were connected", count, nbCpus)
}
```
In `onlineCPUResources`, agent will online cpu until `nbCpus` number of cpus being onlined, otherwise agent will sleep for `onlineCPUMemWaitTime`. It means that if some of cpus are onlined by udev, agent will try `onlineCPUMaxTries` times to traverse cpu folder and sleep for `onlineCPUMemWaitTime`.
So I think we would better select one between udev and onlinecpumem RPC.

**Comment by devimc** [comment]
I agree with @lifupan , we should avoid udev since we have to know if the resources were connected correctly. @jodh-intel I like the solution that you propose but by now we don't need a function with response, we should implement it when we need it

**Comment by sboeuf** [comment]
@bergwolf I think we should definitely wait for the resources to be ready on the guest, or at least make sure we wait for them while we perform some parallel setup. But at some point in the code we should ensure those resources are ready before we let the user play with the container.

**Comment by bergwolf** [comment]
@sboeuf I agree. We should fix the wait logic and make sure we wait for both cpu and memory to be online on both runtime and agent sides. To speed things up, maybe we should only try to wait when these resources are about to be used (IOW, when creating new containers in the agent).

**Comment by sboeuf** [comment]
@bergwolf yes that makes sense.
The way I see things, we should have the agent listening to uevents, this way, anytime it sees some uevents related to CPU or memory, it will try to online them. From the runtime side, when we know that we're about to give the control back to user, we should wait for the resources. By "wait for the resources", I mean that we should be able to specify the amount of memory that we expect to be available. The agent will check if enough blocks are onlined, and in case there's not enough, it should simply online them at this time.
But we should expect that most of the time the agent will have already onlined CPU and memory, meaning that a call such as `WaitForResources()`, should return pretty quickly.
