### ISSUE TITLE
Update github.com/containerd/console in vendor 

### ISSUE THREAD

**Issue by alicefr** [kata-containers/agent#410]
# Description of problem
I'm working on IBM Z support for kata. IBM Z is a big endian architecture and the old version of the `github.com/containerd/console` has a bug. The issue has already been solved for runc see [issue](https://github.com/opencontainers/runc/pull/1727) with this fix in the [console package](https://github.com/containerd/console/pull/20). The `github.com/containerd/console` needs to be updated to include the fix. The bug shows up with `exec` command
```sh
$ bundle="/tmp/bundle"
$ rootfs="$bundle/rootfs"
$ mkdir -p "$rootfs" && (cd "$bundle" && kata-runtime spec)
$ sudo docker export $(sudo docker create busybox) | tar -C "$rootfs" -xvf -
$ kata-runtime --log=/dev/stdout run --bundle "$bundle" foo
# In another terminal
$ kata-runtime exec -t foo
rpc error: code = Internal desc = Could not run process: container_linux.go:348: starting container process caused "open /dev/pts/4294967296: no such file or directory"
```

**Comment by alicefr** [comment]
Could you please help me how can I properly update the `github.com/containerd/console`. The runc commit in [Gopkg.toml](https://github.com/kata-containers/agent/blob/3bef6122c307bf1e562d5c645f45fb4bb66d8053/Gopkg.toml#L15) seems already to include the fix, but the [containerd/console](https://github.com/kata-containers/agent/blob/master/vendor/github.com/containerd/console/tc_linux.go) doesn't include the fix.
```sh
$ cd $GOPATH/src/github.com/opencontainers/runc
$ COMMIT_FIX=59e5b61c5c57a6e8f9ad54860a02cde75a6024db
$ KATA_RUNC=cc4307ab6643668ce5abc6b524e1764a54c32550
$ git merge-base --is-ancestor $KATA_RUNC $COMMIT_FIX; echo $?
1
```

**Comment by caoruidong** [comment]
I think maybe kata code dosen't call into this package. You can add a constrain explicitly in Gopkg.toml.

**Comment by alicefr** [comment]
Do you mean to add the console package in Gopkg.toml as dependency?

**Comment by caoruidong** [comment]
Yes. I don't know why it happens. cc @jodh-intel
