### ISSUE TITLE
Implement a function/request to upload files from host to guest

### ISSUE THREAD

**Issue by devimc** [kata-containers/agent#432]
Implement a function/request to upload files from host to guest, this function/request can be used to replace 9p only when few and small file are shared

**Comment by caoruidong** [comment]
Is there a detailed user scenario?

**Comment by egernst** [comment]
@caoruidong - this is useful for passing in files like _resolv.conf_ and _hosts_ to the guest.  This should be a one way write.  The goal is to move away from being dependent on bind mounting via 9p, and enabling much simpler hypervisors.

**Comment by caoruidong** [comment]
Got it. Thanks
