### ISSUE TITLE
cpu hotplug support on arm64

### ISSUE THREAD

**Issue by hejianet** [kata-containers/agent#471]
# Description of problem

see https://github.com/kata-containers/runtime/issues/1262

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

---

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by justin-he** [comment]
ping  @jodh-intel @grahamwhaley
