### ISSUE TITLE
Add network stats

### ISSUE THREAD

**Issue by ZeroMagic** [kata-containers/agent#535]
# Description of problem

Currently KataContainers collect the stats from libcontainer Stats() API.

The libcontainer Stats() API has collected the network stats. However KataContainers do not transfer the network stats now. Can we add network stats ? The network stats will help us to improve our service quality.

```proto
message NetworkStats {
	string name = 1;
	uint64 RxBytes = 2;
	uint64 RxPackets = 3;
	uint64 RxErrors = 4;
	uint64 RxDropped = 5;
	uint64 TxBytes = 6;
	uint64 TxPackets = 7;
	uint64 TxErrors = 8;
	uint64 TxDropped = 9;
}
```

# Expected result

kata-agent will transfer the network stats to kata-runtime. Then I will also do some work in kata-runtime to convert vc.ContainerStats to containerd/cgroups.Metrics. I have proposed a pull request in containerd/cgroups repo. https://github.com/containerd/cgroups/pull/81

**Comment by bergwolf** [comment]
Looks good! We can proceed once containerd merges containerd/cgroups#81

**Comment by ZeroMagic** [comment]
Ok. We can wait for the merging to be completed
