### ISSUE TITLE
go >= 1.11 required for proper vsock support

### ISSUE THREAD

**Issue by marcov** [kata-containers/agent#542]
(not sure this is really a bug, limitation or just something to note)

When building kata-agent with go < 1.11 (e.g. with go 1.10.4), vsock communication with the host does not work:

```
$ sudo kata-runtime --kata-config configuration-qemu.toml  run --bundle bundle myctr
Failed to check if grpc server is working: rpc error: code = Unavailable desc = transport is closing                                                                                          
```

**Comment by grahamwhaley** [comment]
I would call it a bug today, as the version of golang we have set in our [versions file](https://github.com/kata-containers/runtime/blob/master/versions.yaml#L267) is still 1.10.4 :-)
We should:
 - clarify if we understand why this fails
 - probably bump out minimum golang to 1.11 at least. 1.10.x is now in the ['archived' section](https://golang.org/dl/) of golang releases I think...

**Comment by marcov** [comment]
> I would call it a bug today, as the version of golang we have set in our [versions file](https://github.com/kata-containers/runtime/blob/master/versions.yaml#L267) is still 1.10.4 :-)

The agent does not look at versions.yaml (yet). So it would be worth doing adding the check.

And when building kata-agent in the osbuilder repo, the compiler version is read from [this file](https://github.com/kata-containers/osbuilder/blob/master/rootfs-builder/versions.txt), that as of now it's 1.11 

> We should:
> 
> * clarify if we understand why this fails

Definitely. I am thinking of a way to retrieve agent logs in the guest. Do you have any idea?

**Comment by grahamwhaley** [comment]
I think @marcov if you enable proxy and agent debug, then the agent output will come out in the proxy system logs... I think. /cc @jodh-intel @jcvenegas @devimc

**Comment by devimc** [comment]
@marcov yes , as @grahamwhaley mentioned, you should enable agent+proxy debug. Run `journalctl -b -t kata-proxy` to see the logs

**Comment by marcov** [comment]
@devimc 
But doesn't the agent talk directly with the shim over vsock? 
...and, if the agent does not set up the vsock, then there aren't logs sent to the host.

**Comment by jcvenegas** [comment]
@marcov  does proxy setup work ? if the proxy case does not work probably is something with our code, but if only vsock it may be the code that the agent vendors.

**Comment by marcov** [comment]
The proxy (non-vsock) setup works. The problem is just when vsock is enabled.

**Comment by devimc** [comment]
@marcov you're right, if vsocks is enabled, there is no proxy to read the logs from console.sock

**Comment by devimc** [comment]
we should add support in the shim to read the logs from console.sock if vsock is enabled

**Comment by devimc** [comment]
@marcov you can run socat after having run a container

for example

```
sudo socat stdin,raw,echo=0,escape=0x11 unix-connect:///run/vc/vm/47b0562194c8f3d758f0063d57dca326e33ce0b69dd0a755df4685291486ac80/console.sock
```

**Comment by marcov** [comment]
@devimc thanks for the hint

I retrieved this log:
```
...
[  OK  ] Reached target Kata Containers Agent Target.
[    0.944656] systemd[96]: kata-agent.service: Executing: /usr/bin/kata-agent
time="2019-04-24T17:04:09.736597928Z" level=info msg=announce device-handlers="mmioblk,blk,scsi,nvdimm" name=kata-agent pid=96 source=agent storage-handlers="ephemeral,local,9p,virtio-fs,blk,mmioblk,scsi" system-memory="2041344 kB" version=1.7.0-alpha1-455cb796fea84006f3434c9a96af9195121f20b2
time="2019-04-24T17:04:09.737249982Z" level=debug msg="Vsock channel type detected" name=kata-agent pid=96 source=agent
time="2019-04-24T17:04:09.737543272Z" level=info msg="Started listening for uevents" name=kata-agent pid=96 source=agent subsystem=udevlistener
time="2019-04-24T17:04:09.737913097Z" level=info msg="agent grpc server starts" name=kata-agent pid=96 source=agent
time="2019-04-24T17:04:09.738355053Z" level=info msg="Waiting for stopServer signal..." name=kata-agent pid=96 source=agent subsystem=stopserverwatcher
time="2019-04-24T17:04:09.901253908Z" level=debug msg="new request" name=kata-agent pid=96 req= request=/grpc.Health/Check source=agent
time="2019-04-24T17:04:09.919635858Z" level=debug msg="request end" duration="22.681µs" name=kata-agent pid=96 request=/grpc.Health/Check resp="status:SERVING " source=agent
```

**Comment by devimc** [comment]
not sure, but might be it could be related to https://github.com/kata-containers/agent/pull/507

**Comment by jodh-intel** [comment]
@marcov - to grab agent logs when vsock is being used, we currently have to rely on https://github.com/kata-containers/agent/blob/master/TRACING.md#guest-journal-redirector.

**Comment by marcov** [comment]
> not sure, but might be it could be related to #507

yep, that's it, as documented on the vosck [landing page](https://github.com/mdlayher/vsock#go-version-support), go <= 1.10 is not supported.

I am not sure what's the best way to add  the go version check here. I dont want to bloat the osbuilder image creation by adding a dependency on the runtime repo. Let's see if [adding a  compile time check](https://github.com/mdlayher/vsock/pull/34) of the Go version over the vsock package is enough.

Other ideas are welcome :-)

**Comment by devimc** [comment]
@marcov I'm adding support to the shim and runtime to print the agent logs if there is no proxy, see https://github.com/kata-containers/shim/pull/172
