### ISSUE TITLE
sandbox init process should has its own empty mnt ns

### ISSUE THREAD

**Issue by laijs** [kata-containers/agent#57]
related to hyperhq/hyperstart#326

We can use a new mountns for sandbox_pidns and make the
sandbox_pidns process's rootfs as an empty dir.

**Comment by jodh-intel** [comment]
Looks like this is still outstanding: https://github.com/kata-containers/agent/blob/master/namespace.go#L32..L34.

Any takers? @sboeuf? @bergwolf?

**Comment by jcvenegas** [comment]
This is does not affect kata closing issue.

docker run -ti --rm --runtime kata-qemu ubuntu cat /proc/1/root/etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
