### ISSUE TITLE
add health check in the api

### ISSUE THREAD

**Issue by laijs** [kata-containers/agent#58]
The guest/agent may stall on some cases or panic. but the vm look normal out side.
health check can be used to check this situation. In hyperstart runtime call the Version()
api periodically. In kata, we also need such mechanism.

[grpc health check](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) might help.

**Comment by sboeuf** [comment]
@laijs could you provide a description of this one please ?

**Comment by laijs** [comment]
@sboeuf I updated in the top post in this issue. A mechanism is required to check the health of the agent.

**Comment by sboeuf** [comment]
@laijs thanks ! Oh so you mean something like a heartbeat control. This sounds good to me.

**Comment by laijs** [comment]
We'd better to provide the API. It is OK a runtime implementation won't use it. but runv is going to use it.

**Comment by WeiZhang555** [comment]
> grpc health check might help.

:+1:  I agree, this is necessary and grpc health check could be helpful.
