### ISSUE TITLE
agent sandbox shared pidns is broken on alpine rootfs

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/agent#584]
# Description of problem

When I change kata runtime to create sandbox with `sharePidNs` to be true, container creation will always fail.

# Expected result

Container is created successfully.

# Actual result

Container creation failed.

# Analysis

After some digging, I found out that the root cause is on the pause binary. We use cgo `__attribute__(constructor)` to re-exec the agent as a pause process to hold the shared pidns. It works well on glibc. However, on alpine which uses musl libc, it fails because the `__attribute__(constructor)` cannot access main function arguments (argc, argv) and as a result the pause process always quits very quickly. It (constructor functions taking arguments) is a glibc specific feature only available on i386 and x86_64 architectures. So we cannot rely on `__attribute__(constructor)`.

**Comment by devimc** [comment]
see #620 #621 

cc @bergwolf

**Comment by jodh-intel** [comment]
Sounds like we're missing a test over in https://github.com/kata-containers/tests for this scenario.
