### ISSUE TITLE
agent: Hostname not set for sandbox/VM

### ISSUE THREAD

**Issue by nitkon** [kata-containers/agent#586]
```
root@nitkon:/home/nitesh# bash -x connect_debug.sh 
++ sudo docker ps -q --no-trunc
+ id=cbb8ec2e63001340f2aba78a455d1762fdd5f4969f3829a2a857c7200abe23bb
+ console=/var/run/vc/vm/cbb8ec2e63001340f2aba78a455d1762fdd5f4969f3829a2a857c7200abe23bb/console.sock
+ sudo socat stdin,raw,echo=0,escape=0x11 unix-connect:/var/run/vc/vm/cbb8ec2e63001340f2aba78a455d1762fdd5f4969f3829a2a857c7200abe23bb/console.sock

bash-4.4# hostname
(none)
bash-4.4# 
```

As part of [CreateSandbox](https://github.com/kata-containers/agent/blob/629f90f9ff2065509d46192325e6409bdaacef79/grpc.go#L1407) I see the sandbox hostname getting set. 
After attaching to the console of the kata VM, I could see the hostname not set.

**Comment by amshinde** [comment]
@nitkon We set the hostname in the UTS namespace that we create for the containers, and not within the VM itself. Thats why you are seeing this behaviour. We just need to make sure the hostname is correct in the namespace for the containers.

**Comment by nitkon** [comment]
Hi @amshinde , my intention is to set hostaname and dns for the guest VM. 
Ptal: https://github.com/kata-containers/runtime/pull/1825 and https://github.com/kata-containers/agent/pull/590
