### ISSUE TITLE
Seeing a stream of warning messages when setting up debug console with kubernetes.

### ISSUE THREAD

**Issue by amshinde** [kata-containers/agent#587]
On setting up debug console with kubernetes pod, I am seeing a stream of warning message on the debug console:
```
time="2019-06-21T23:35:21.762247108Z" level=warning msg="cpu is not in guest cpu list, using guest cpus" cpu=1 cpuset=0-3 guest-cpus=0 name=kata-agent pid=80 sandbox=fe8e6e345bc9a572e4f16a6a734f763a82d9a00d6b7ced2f6bd0d334d3efba1f source=agent
time="2019-06-21T23:35:31.884159759Z" level=warning msg="cpu is not in guest cpu list, using guest cpus" cpu=1 cpuset=0-3 guest-cpus=0 name=kata-agent pid=80 sandbox=fe8e6e345bc9a572e4f16a6a734f763a82d9a00d6b7ced2f6bd0d334d3efba1f source=agent
```

The pod did not have any resource constraints.

**Comment by amshinde** [comment]
We need to look into why these warnings are generated. If these are benign messages, then we should turn these to debug messages, as currently the debug console is quite unusable with these messages being printed to the console continuously.

cc @jcvenegas @egernst

**Comment by jcvenegas** [comment]
@amshinde are you using static cpu policy?, I think those warnings are to just not apply cpuset if is not possible

**Comment by amshinde** [comment]
@jcvenegas Yes, This is the one used for the clear-linux stack as well:
https://github.com/clearlinux/cloud-native-setup/blob/master/clr-k8s-examples/kubeadm.yaml#L7

I had to manually patch the agent and install it the rootfs to get around this.

**Comment by jcvenegas** [comment]
@amshinde interesting, this warnings actually where to prevent the container execution failed (instead of just fail). What are the additional changes you needed to add?

**Comment by amshinde** [comment]
@jcvenegas I just commented out this line:
https://github.com/kata-containers/agent/blob/master/cgroup.go#L55

So that I could type things on the debug console again without being interrupted by the continuous warning messages.

**Comment by jcvenegas** [comment]
oh I see what you mean, It is just a very annoying. Yeah make sense, probably we can change the log from warn to debug. This happend all the time because k8s keeps doing a `kata-runtieme update` per each container.
