### ISSUE TITLE
[RFC] Always create sandbox init process and knobs for joining

### ISSUE THREAD

**Issue by laijs** [kata-containers/agent#59]
In hyperstart, the pod_init process has its own net/pid/uts/ipc ns.

And in kata, these namespaces are also essential.

Net ns for the sandbox should be always created since the container's
network should be isolated from the vm's initial network to
avoid messing.

Pid ns for the sandbox should be always created since the containers
always join this ns. We can use new pid ns for each container,
but in most cases, they are shared the same sandbox init pid ns.

Uts ns for the sandbox should be always created since the hostname
is set in it without mess it up with the vm's initial UTS.

Ipc ns for the sandbox should be always created since the containers
always join this ns. We can use new ipc ns for each container,
but in most cases, they are shared the same sandbox init ipc ns.

So sandbox init process should be always created
in its own net/pid/uts/ipc ns and let the later containers
join in. __A pr is required for it__

__In above info, we know that container should always join the net/uts ns.
And container should NOT use the guest's initial pid/ipc ns.
But container can use the shared or private pid/ipc ns.
We have knob for pid ns. Should we add a knob for the ipc ns?
Or we can make it always to be one of shared or private.__

**Comment by bergwolf** [comment]
I agree that new namespaces should always be created and we let runtime specify what is shared/private via the OCI spec. The agent should check to make sure no containers join the agent's namespace (except for the user ns?).
