### ISSUE TITLE
add grpc version API

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/agent#61]
We will need a version mechanism for agent gRPC. The most likely case we will want to handle is runtime upgrading and it reconnects to an old agent. While we can keep gRPC API backward compatibility, runtime needs to know this situation and take care not to send new API requests to old agents.

We can start by having a version check API first. And it can live with the health check service.

**Comment by WeiZhang555** [comment]
:+1:

**Comment by sboeuf** [comment]
@bergwolf I like the idea of adding a version, but I am wondering what's the benefit of having both `Version()` and `HealthCheck()` in a separate service ?

**Comment by bergwolf** [comment]
@sboeuf It was implemented as a separate service because the [GRPC Health Checking Protocol](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) suggested so.

**Comment by sboeuf** [comment]
@bergwolf Fair enough, thanks for the reference.
LGTM
