### ISSUE TITLE
Enable opencensus on the agent

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/agent#673]
Here are some general questions that I have about the current tracing implementation and the one that it will be implemented
1. I understand that we will use the host.go from (https://github.com/mcastelino/custom_exporter/) at the host and that I need to modify the tracing.go (to include part of the vm.go code from Manohar's). The set of changes involve to remove the use of the "github.com/uber/jaeger-client-go/config", removing the use of the `jaeger-client-socat-redirector.service`,
`kata-redirect-agent-output-to-journal.conf` and `kata-journald-host-redirect.service` as they are use as a way to communicate Jaeger client code with the jaeger agent on the host (vsock limitation). Are these asumptions correct? Now this also will have an impact on the Makefile as they are part of it.
2. Is there a way that I can test the changes that I am doing at the tracing.go? I tried to build it alone and it seems that is not possible as you need to compile or build everything.
3. Currently, I submitted some PRs https://github.com/kata-containers/agent/pull/671 and https://github.com/kata-containers/agent/commit/3e625657823249a7ffdb35d5d04f573d61053c43 in order to make easier the changes of the name of the functions as I see on the opencensus API the way that we for example set a tag is different for the opentracing stuff.

**Comment by GabyCT** [comment]
@jodh-intel , I have a question regarding https://github.com/kata-containers/agent/blob/master/agent.go#L245, what is the purpose of this function? I see that is enabling a trace but why this is not done with something like `tracer := opentracing.GlobalTracer()` which helps to start a trace? 
Also, I have a question regarding https://github.com/kata-containers/agent/blob/master/agent.go#L294 . I am a little confused about these two implementations. thanks

**Comment by jodh-intel** [comment]
Both `container.trace()` and `sandbox.trace()` are doing similar things:

- Setting the context to the "default" context if the caller forgot to provide a context.

  That's important as it's a bug (hence the log calls), but we don't want to stop tracing from working in the scenario where a user is somehow exercising an unusual code path.

- Calling the main `trace()` function to add some useful trace *tags* in a generic manner.

A global tracer call wouldn't do either of these things.
