### ISSUE TITLE
Add ability to configure hotplugTimeout

### ISSUE THREAD

**Issue by awprice** [kata-containers/agent#683]
**Is your feature request related to a problem? Please describe.**

We've noticed when the host is experiencing high CPU load, occasionally hotplugging of block devices into new guests can slow down. This results in the current timeout (3 seconds) being reached whilst waiting for the block device to be plugged in.

We then see the pod fail with the following in the containerd logs:
```
E1027 22:10:19.901468    3217 pod_workers.go:190] Error syncing pod 6ebfa25e-f906-11e9-b214-0a6e816c85ea ("b86a270f-68c8-43ad-afe3-f8f5461392c4_b86a270f-68c8-43ad-afe3-f8f5461392c4(6ebfa25e-f906-11e9-b214-0a6e816c85ea)"), skipping: failed to "StartContainer" for "build" with RunContainerError: "failed to create containerd task: Timeout reached after 3s waiting for device 0:0:0:3/block: context deadline exceeded"
```

**Describe the solution you'd like**

We would like to have a configurable option for the timeout. At the moment it is hard coded to 3 seconds - https://github.com/kata-containers/agent/blob/dfbcc01c5444a344e98a85986a012c5b3412181f/device.go#L48

A flag passed through `kernel_params` to control the timeout would be ideal, defaulting to the current value of 3 seconds if not specified.

**Describe alternatives you've considered**

No other alternatives other than reducing the high CPU load.

**Additional context**

N/A

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)? *Yes*

**Comment by devimc** [comment]
@awprice thanks for raising this, some questions:

Are you using block or scsi devices ? https://github.com/kata-containers/runtime/blob/master/cli/config/configuration-qemu.toml.in#L137

How many block devices did you hot plug?

what timeout value works for you?

**Comment by awprice** [comment]
@devimc 

- We are using virtio-scsi.
- We hot plug between 2-6 block devices - it really depends on the workload being run. 
- We aren't too sure on the timeout yet.

**Comment by egernst** [comment]
This seems pretty reasonable to me.

@bergwolf @gnawux - ya'll have input here?

**Comment by awprice** [comment]
I've had a go at implementing this - https://github.com/kata-containers/agent/pull/685

Let me know what you think of the implementation and whether it is the correct approach.
