### ISSUE TITLE
maintain kata agent API compatibility

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/agent#684]
**Is your feature request related to a problem? Please describe.**

We've defined the kata agent API version. However, we've never really maintained its compatibility, and have brought in broken changes from time to time. Right now kata project is relatively stable and we should start considering API stability and compatibility.

**Describe the solution you'd like**

1. have a clear definition of agent API compatibility plan and document it
2. define compatible agent API change and incompatible agent API change
3. figure out how to handle old runtime vs. new agent scenario
4. figure out how to handle new runtime vs. old agent scenario

**Additional context [WIP]**

# 1. Agent API Compatibility Requirement
* 1.1 - Incompatible API change can only be merged when publishing new kata releasing
* 1.2 - Compatible API change can be merged at any time when approved
* 1.3 - Changed agent API must be maintained for at least two release cycles

# 2. Definitions
## 2.1 Compatible API Change
Agent API change that does not require newer runtime or agent to work with.

## 2.2 Incompatible API Change
Agent API change that requires either newer runtime or newer agent to work with.

# 3. Agent API Maintenance Alternatives
### 3.1.1 Versioned Agent GRPC Server
The idea is to maintain Agent grpc at different endpoints based on API versions. Right now we have two service endpoints:
* grpc.AgentService taking path `/grpc.AgentService/<API_Name>`
* grpc.Health taking path `/grpc.Health/<API_Name>`

And we can add API versioning to the path, e.g.,
* grpc.AgentService version `123` taking path `/grpc.AgentService.123/<API_Name>`

We don't change `grpc.Health` service as we need it to get agent service version.

It means we need to define different agent.proto for each API version, and maintain grpc implementations for each for them.

### 3.1.2 Versioned Runtime GRPC Client
Like in the agent, we maintain different grpc client implementation on the client side, and choose which one to use based on server versions.

### 3.1.3 Old runtime talking to new agent
Because old agent API grpc service is still maintained, there is no trouble for an old runtime to talk to it.

### 3.1.4 New runtime talking to old agent
Because runtime has old grpc client, there is no issue for a new runtime to talk to an old agent. However, it is possible that a new runtime functionality requires a new agent to work. In such case, the runtime should fail properly instead of crashing or creating internal errors.

### 3.1.5 Deprecating An API
No extra work needed. Just remove it when its life ends.

## 3.2 Simple+Complex Method
On the agent side, if we:
* never delete or modify a method arguments
* handle all arguments the same as before 
* never introduce a new argument that conflict with an existing one

Then it is possible for us to just use the one grpc service on the server side. On the client side, it still needs to maintain different grpc client implementations in order to take to old agents. And the runtime client needs to query the health service for actual server API versions.
### 3.2.1 Deprecating An API
When we want to remove an existing API or an argument of an API, we need to handle it the same as before for as long as the `Agent API Compatibility Requirement` states. Then we can drop it.

## 3.3 Others?
Please suggest here.

# 4. Testing
Once the feature rolls out, we should definitely set up tests to validate inter-operability of different runtime and agent versions to make sure we don't bring in unexpected broken changes.

**Comment by grahamwhaley** [comment]
Would this benefit from input from @jon 's legendary 'grpc best practices' PR (that we never managed to land) - https://github.com/jon/kata-documentation/blob/71a506c739f69ea6a431ba9f3bfe6e2bff7816f3/best-practices/grpc-apis.md

**Comment by bergwolf** [comment]
@grahamwhaley Yes, definitely!

**Comment by bergwolf** [comment]
@kata-containers/architecture-committee @kata-containers/agent @kata-containers/runtime please share your thoughts on this.
