### ISSUE TITLE
setupDNS() in guest rootfs will cause a grpc error in CreateSandbox

### ISSUE THREAD

**Issue by YvesChan** [kata-containers/agent#692]
# Description of problem

kata-agent will try to create `/etc/resolv.conf` in guest rootfs while there's a mount destination is `/etc/resolv.conf`. But the guest rootfs has changed to ro mount status (according to https://github.com/kata-containers/runtime/issues/1389), so there's no way for kata-agent to create this file in guest rootfs. And we got a grpc error in pod sandbox creation.

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

**Comment by YvesChan** [comment]
Reference kata-containers/agent#635

**Comment by devimc** [comment]
@YvesChan kata-agent fails because first it tries to bind-mount `resolv.conf` as rw, but since it doesn't exist, kata-agent tries to create it. Please update your rootfs image, or mount it and create `resolv.conf` by hand, for example:

```
sudo losetup --show -Pf kata-containers.img
sudo mount /dev/loop0p1 /mnt
sudo touch /mnt/etc/resolv.conf
sudo umount /mnt
sudo losetup -d /dev/loop0
```

**Comment by YvesChan** [comment]
> @YvesChan kata-agent fails because first it tries to bind-mount `resolv.conf` as rw, but since it doesn't exist, kata-agent tries to create it. Please update your rootfs image, or mount it and create `resolv.conf` by hand, for example:
> 
> ```
> sudo losetup --show -Pf kata-containers.img
> sudo mount /dev/loop0p1 /mnt
> sudo touch /mnt/etc/resolv.conf
> sudo umount /mnt
> sudo losetup -d /dev/loop0
> ```

Yes, I have noticed that. But I think this feature seems not really important in the whole container creation process. The rootfs image we are using is based on an old version of clearlinux image, and this feature break the compatitive, as it assume this file should exist in guest. Is it reasonable for runtime/agent to rely on the version of rootfs image/osbuilder ?
And maybe the release note should point it out :)
Anyway, thank you guys.
