### ISSUE TITLE
vendor: Update libcontainer vendoring version

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/agent#70]
We should bump the vendoring version of libcontainer in order to get the fix https://github.com/opencontainers/runc/pull/1678 included in our code.
This will prevent libcontainer from waiting SIGKILL'ed processes.

**Comment by vbmade2000** [comment]
Can I work on this ?

**Comment by jodh-intel** [comment]
Hi @vbmade2000 - sure! You probably want to read the following if you haven't already done so:

- https://github.com/kata-containers/agent/blob/master/CODE_OF_CONDUCT.md

**Comment by jodh-intel** [comment]
... also, although it's not actually part of the kata project, you might want to have a read of https://github.com/clearcontainers/runtime/blob/master/CONTRIBUTING.md as that's the process we're tending to follow (we need to add CONTRIBUTING.md docs to the kata repos "real soon now" (TM) :smile:)

**Comment by vbmade2000** [comment]
@jodh-intel Sure. I'll take a look on both links. If the same https://github.com/clearcontainers/runtime/blob/master/CONTRIBUTING.md file you want to put then I can put it in this repo :)

**Comment by jodh-intel** [comment]
Thanks @vbmade2000.

---

Regarding the contributing file, that would of course need to be a different PR. We'll need to get agreement from the team of course.

I was in fact imagining we would store a central `CONTRIBUTING.md` file in one of these two repos:

- https://github.com/kata-containers/documentation
- https://github.com/kata-containers/community

We would then then create a 1-line "stub" `CONTRIBUTING.md` file in each of the other kata repos saying something like:

> See https://github.com/kata-containers/.../blob/master/CONTRIBUTING.md.

That way, there is only 1 file to update and we don't end up with some repos out of sync with others if we ever need to update the file.

But what do you think @sameo, @gnawux, @grahamwhaley, @laijs ?

**Comment by jodh-intel** [comment]
Hi @vbmade2000 - responding to your slack question here, yes, I think we need to update to the latest `libcontainer`. If we look at the top few commits of https://github.com/opencontainers/runc/ commits, we see:

```
$ git log -5 --oneline
96086e5 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #1683 from vikaschoudhary16/runc-systemd-race
d5b4a3e Fix race against systemd
e6516b3 Merge pull request #1678 from sboeuf/sboeuf/subreaper
7f24b40 Merge pull request #1675 from tklauser/apparmor-no-cgo
db093f6 libcontainer: remove dependency on libapparmor
```

We need commit `e6516b3` so you'll need to run something like the following to update the vendoring:

```
$ cd $GOPATH/src/github.com/kata-containers/agent
$ go get -u -v github.com/golang/dep/cmd/dep
$ dep ensure -update github.com/opencontainers/runc
$ dep prune
```

Does that sound right @sboeuf?

**Comment by jodh-intel** [comment]
@vbmade2000 - if you don't mind, I'm going to raise a PR for the centralised `CONTRIBUTING.md` doc. I'd like to have something in place relatively quickly plus I need to make some changes to clarity the process. I'll report back on this PR once I've raised the other one. We can then all comment on the doc PR...

**Comment by sboeuf** [comment]
@vbmade2000 as @jodh-intel mentioned, if you want to revendor, you will have to download dep with:
```bash
$ go get -u -v github.com/golang/dep/cmd/dep
```
And then you will have to go to your agent directory in order to bump the version of the libcontainer package:
```bash
$ cd $GOPATH/src/github.com/kata-containers/agent
```
Here you will modify `Gopkg.toml` and you will change the `revision =` corresponding to the package `github.com/opencontainers/runc`.
After that, make sure you run those dep commands:
```bash
$ dep ensure
$ dep ensure -update github.com/opencontainers/runc
$ dep prune
```
The first one `dep ensure` will update `Gopkg.lock` by generating a new `inspect-hash`. Then `dep ensure -update github.com/opencontainers/runc` will ask `dep` to bump the vendoring only for this package.
At last, `dep prune` will make sure to remove any file added by the vendoring which is actually not needed by our code.

**Comment by vbmade2000** [comment]
@jodh-intel - Sure. No worries. 

@sboeuf  @jodh-intel  Thanks for guidance . I already did this manually and pushed but will raise a new PR according to your instructions.

**Comment by jodh-intel** [comment]
I've now raised https://github.com/kata-containers/community/pull/9 for adding a contributions doc (for the overall project, not just the agent repo).
