### ISSUE TITLE
Add support for configuring nvidia GPU access for container

### ISSUE THREAD

**Issue by RyanAoh** [kata-containers/agent#735]
### some related issues ：
https://github.com/kata-containers/runtime/issues/2269
https://github.com/kata-containers/agent/issues/709
https://github.com/kata-containers/documentation/issues/517
https://github.com/kata-containers/runtime/issues/1876

There are two questions：
1. When to load nvidia-kernel module
Nvidia kernel module can't be loaded when there is no device to drive, so , it can't be loaded using kata configuration file  or systemd scripts. We need to distinguish the container  which has gpu vfio device invoked  with '--device' , and load nvidia kernel modules at the right time(after devices added).
2. How to share the driver files（libs, bins）at kata-vm（container‘s host） to container
Reference [nvidia-container-runtime](https://github.com/NVIDIA/nvidia-container-runtime) ：“ A modified version of runc adding a custom pre-start hook to all containers.If environment variable NVIDIA_VISIBLE_DEVICES is set in the OCI spec, the hook will configure GPU access for the container by leveraging nvidia-container-cli from project libnvidia-container”.
We need to do the same thing to configure GPU access for the container. Because we can't let user  modify Dockerfile to install driver files every time when a container is started, it's  inefficient and complicated for users. 

### Solution：
1. Like nvidia-docker， set env “NVIDIA_VISIBLE_DEVICES”（in device-plugin, Dockerfile, or command args）to distinguish the gpu container, then call function to setup nvidia driver for the container.
2. setup nvidia driver for container :
  + exec "[nvidia-container-cli](https://github.com/NVIDIA/libnvidia-container) --kernel-modules info " to load nvidia kernel modules and get gpus info
  + exec "nvidia-container-cli list --binaries","nvidia-container-cli list --libraries" list the neccessary driver files
  + mount the binaries and libraries listed before to the container's rootfs
  + exec "ldconfig" to configure dynamic linker run-time bindings
> nvidia-container-cli and nvidia kernel modules should be instlled to kata-vm when building the rootfs.

#### Test result
Actually, I have done some tests in the way above，it can achieve the same effect as nvidia-docker.

+ Docker:
![image](https://user-images.githubusercontent.com/13352465/74536749-a7024a80-4f73-11ea-9916-4dbe8ca541dc.png)
![image](https://user-images.githubusercontent.com/13352465/74536860-e16be780-4f73-11ea-90dc-c89fb63e4092.png)

+ kubernetes(with my own device-plugin)
![image](https://user-images.githubusercontent.com/13352465/74536930-0b250e80-4f74-11ea-811e-1994341aeae4.png)

**Comment by RyanAoh** [comment]
I have added and tested these code in my own project.  If the solution is OK,  I'd like to submit a PR.

**Comment by devimc** [comment]
yes please, submit a PR, I'll glad to to review it

**Comment by dalfos** [comment]
Hi @RyanAo. How to install nvidia-container-cli and nvidia driver into rootfs?

**Comment by chestack** [comment]
"in kata Guest vm,  configure nvidia GPU access for container"  this is really needed
