### ISSUE TITLE
[RFC] Object ID

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/agent#75]
Hello,

I would like to propose that we enforce a design pattern when runtime creates objects through agent gRPC APIs -- **for every object, it has a unique ID that is irrelevant to the actual implementation of the object and can identify the object within a certain scope**.

To be specific, a container has a container id, a process has a process id, a storage has a storage id, a volume has a volume id, an interface has an interface id, a device has a device id, etc.

With above, we get a common pattern for all objects, instead of letting container/storage/volume/device have runtime designated IDs, while process/interface in turn uses their internal implementation related pid and MAC address as identifiers. And this would close the long-running discussions around #56 and #72 

WDYT @sameo @sboeuf @WeiZhang555 @laijs @gnawux @mcastelino

**Comment by sameo** [comment]
cc @tallclair

**Comment by sameo** [comment]
I want to point out that processes, storage, devices and NICs have unique host and guest identifiers. The kernel manages and uniquely identifies them, so I wonder why we need another abstraction layer on top of it.

**Comment by bergwolf** [comment]
@sameo I want the abstraction because then we do not need to look into details of each object to find out which is a possible unique identifier and thus end the ever-running discussions like whether pid/MAC is validly unique in a guest.

BTW what do you think can uniquely identify a storage? Device path cannot work because it may not have one at all. And mountpoints can easily duplicate.

**Comment by WeiZhang555** [comment]
I was also thinking about this recently, I think this is a good idea, which will end all `unique key` related talks. With something like `UUID` system, we can make the design more consolidated. One good example is in database world, every record has a unique number index when we design the table.

/cc @jodh-intel @sboeuf for more discussions.

**Comment by bergwolf** [comment]
@sameo now that we've agreed that a runtime generated process ID works better than guest pid in #72, is it OK to push the similar object ID rule globally?

**Comment by sboeuf** [comment]
I am fine with that, since it is not going to change anything, it's more about a concept we all agree on.

**Comment by c3d** [comment]
This was not done since it was suggested. I believe we should close it, and re-open the issue if we actually start working on it. @bergwolf please reopen if you think it is wrong to close it.
