### ISSUE TITLE
CPU hotplug for AArch64

### ISSUE THREAD

**Issue by stevecapperarm** [kata-containers/agent#764]
(this duplicates https://github.com/kata-containers/agent/issues/471, I thought it better to start a new thread)

Hello, I work with @justin-he at Arm,
We are trying to add a mechanism to Kata to allow CPUs to be added to guests for Arm.
 
There was a pull request and discussion at: https://github.com/kata-containers/agent/pull/478

I am raising this issue as an update to some of the questions asked during the above thread.

Arm supports CPU online/offline, but the CPUs remain present. It does not currently support CPU add/remove.
(CPU add/remove would require specification work, hypervisor support, kernel support and VMM support)
Unfortunately, it is not clear when CPU add/remove will be available. (Also, any mechanisms for virtual CPU add/remove would need to be valid for the physical CPU add/remove case).
 
Going forwards we would still like to add a capability to "add"/"remove" CPUs to Kata, but we won't be able to extend the ACPI technique.
 
In fact I was going to recommend @justin-he's pull request as a basis to start this off.
 
There are ramifications for resource cost namely that:
 * Guest kernels will need to boot the "unneeded" CPUs before offlining them,
 * There is a memory cost associated with the vCPUs in KVM, the guest kernel and the VMM.
 
(The resource costs above could potentially be mitigated to a degree by enhancements to KVM/Linux kernel/VMM if this approach gains traction).
 
However there is one advantage of the online/offline technique:
 * CPU online/offline would be VMM agnostic - it would only require a -maxcpus argument
 
The main reason I'm raising this is because I am based in the United Kingdom, and have better timezone overlap with the States, so am able to attend any calls/IRC chats if that's helpful?
 
Would it be possible to re-consider the CPU online/offline approach?
 
Cheers!
--
Steve Capper

**Comment by devimc** [comment]
the problems I see with the `online/offline cpus through gRPC`  approach are:
* the resources (threads in the host) for offline vcpus are not freed, (like zombie threads.. ?)
* Memory footprint: guest kernel needs more memory to handle all the (offline/online) vcpus
* Boot time: guest kernel needs more time to initialize all the vcpus
* Security: a malicious workload able to scape from the container in the guest would be able to online all the vcpus and throttle the host

**Comment by stevecapperarm** [comment]
Hi,
For the resource costs, yeah, there would be more memory consumed and a longer boot time unfortunately. :-(

It's my understanding that having threads for offline CPUs shouldn't cause an issue during normal execution - they won't be scheduled, so won't consume CPU. Or have I overlooked something?

Regarding the security aspects around denial of service being amplified by the guest spuriously soft-onlining CPUs. Would it be possible to mitigate against this by applying cgroup parameters (cpu.shares?) or by setting CPU affinity of the VMM?

**Comment by grahamwhaley** [comment]
My gut, and our past experience, tells me we are unlikely to adopt the mechanism for other architectures if it has memory and/or boot time impact. Feels like we might have to have different methods across architectures then.

**Comment by jodh-intel** [comment]
This sounds like a good topic for the Architecture Committee meeting (Tuesday at 8am PDT) if you want to add it to the etherpad agenda?

- https://etherpad.openstack.org/p/Kata_Containers_2020_Architecture_Committee_Mtgs
- https://katacontainers.io/community/
- https://github.com/kata-containers/community/#architecture-committee

**Comment by jodh-intel** [comment]
@jongwu - do you have any thoughts on this?

**Comment by ariel-adam** [comment]
Do we want to close this or push it forward :-)?

**Comment by justin-he** [comment]
@jodh-intel @ariel-adam The qemu/kernel patch series had been posted to upstream for review by Huawei experts. I can close it temporarily. And discuss it again after upstream merges vcpu hotplug feature on arm64

**Comment by justin-he** [comment]
@stevecapperarm What do you think of it? seems I don't have the access to close it ;-)

**Comment by jodh-intel** [comment]
@justin-he - I'll close for now then. Either re-open or raise a new issue if we want to revisit this in the futre.
