### ISSUE TITLE
sharePidns would cause zombie process leak in the container 

### ISSUE THREAD

**Issue by lifupan** [kata-containers/agent#803]
# Description of problem

Since the sharedpidns  init process hasn't the child reap function, thus there is no init process would reap 
the zombie process in the container. for much info please see https://github.com/kata-containers/runtime/pull/2794#event-3517183039.

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by ariel-adam** [comment]
@lifupan Could clarify this bug?
What exactly is the problem including the expected result and actual result

**Comment by jodh-intel** [comment]
Hi @lifupan - please could you clarify - is this still an issue? If not, please could you provide the issue/PR number?

**Comment by lifupan** [comment]
> Hi @lifupan - please could you clarify - is this still an issue? If not, please could you provide the issue/PR number?

Hi @jodh-intel 

Actually this issue is specific to share sandboxpidns when createsandbox requested as https://github.com/kata-containers/agent/blob/master/grpc.go#L1490.   But by now it seemed we hadn't used this feature, and we only  do share the sandbox pid ns with the pause container's init process instead of create an separated pause process,  thus I think I can close this issue temporarily.
