### ISSUE TITLE
guest OCI hooks are not working with Kata

### ISSUE THREAD

**Issue by bpradipt** [kata-containers/agent#818]
# Description of problem
OCI hooks are not working with Kata. Created a rootfs with hook scripts and enabled guest_hook_path = "/usr/share/oci/hooks" in the configuration.toml.
Running the container results in the following error:

Error response from daemon: OCI runtime create failed: rpc error: code = Unknown desc = open /run/kata-containers/shared/containers/7217217f69ef8af65581790aa06fe3b54499dd3b8f1a79e6116
94ec670a6182a/config.json: read-only file system: unknown.
time="2020-06-10T11:49:58Z" level=error msg="error waiting for container: context canceled"
The problem got introduced since the following commit a3dec26

# Expected result
Container should start and hooks should run

# Actual result
Container fails to start.

Reference Issue - https://github.com/kata-containers/runtime/issues/2763

**Comment by jodh-intel** [comment]
Closing as PR is already merged.
