### ISSUE TITLE
agent: Add missing nsenter import

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/agent#95]
It is mandatory that we import `nsenter` package, otherwise the `init()` function won't be able to spawn a new container.
This line has to be added to `agent.go`:
```go
import (
        ...
        _ "github.com/opencontainers/runc/libcontainer/nsenter"
        ...
)
```

This requirement comes from the libcontainer documentation here: https://github.com/opencontainers/runc/blob/master/libcontainer/README.md
It explains that we need to add this import so that it will handle part of the container bootstrapping.
More details here: https://github.com/opencontainers/runc/blob/master/libcontainer/nsenter/README.md

**Comment by vbmade2000** [comment]
Can I work on this simple issue ?

**Comment by sameo** [comment]
@vbmade2000 Yes, please do.

**Comment by vbmade2000** [comment]
@sboeuf  There does not exist github.com/opencontainers/runc/libcontainer/nsenter path. in vendors  It exists in runc repo in release v1.0.0-rc4.

**Comment by jodh-intel** [comment]
@sboeuf - when you are back tomorrow, could you also add a bit more detail to this issue explaining why the container spawn will fail?

**Comment by sboeuf** [comment]
@jodh-intel I have updated the issue description.

**Comment by jodh-intel** [comment]
Thanks @sboeuf.

**Comment by sboeuf** [comment]
@vbmade2000 I don't get what is the problem here ? The vendoring of `github.com/opencontainers/runc` refers to the version 1.0.0-rc4 as you mentioned. And the `nsenter` package does exist for this version.
Now if what you mean is that nsenter is not into the `/vendor/...` directory, this will be solved by first modifying the code so that you actually import `_ "github.com/opencontainers/runc/libcontainer/nsenter"`, and then by running the following command:
```bash
dep ensure && dep ensure -update github.com/opencontainers/runc && dep prune
```

**Comment by sameo** [comment]
@vbmade2000 You need to add the import into the code and then `dep` will detect this new dependency and add `nsenter` to the vendoring path.

As @sboeuf said, you need to run:

```
dep ensure -v && dep ensure -update -v github.com/opencontainers/runc && dep prune -v
```

**Comment by sboeuf** [comment]
@vbmade2000 are you still planning on implementing this ?
I am sorry to rush you here but we're trying to enable our runtime with the Kata agent, and we would need this to be merged asap.

**Comment by vbmade2000** [comment]
@sboeuf I am done with it. Raising PR now.

**Comment by sboeuf** [comment]
Cool thank you :smile:
